/**
 * mobile_models_c.h  --  MobileCNN-1D and MobileCNN-SE-1D forward passes.
 *                         int32 variant: no float, no math.h.
 *
 * Both models share the same input/output interface as run_cnn_1d_v2():
 *   input_data : 570 int32_t values in channel-first layout (ch * 10 + t),
 *                or NULL for seeded dummy data (benchmarking only).
 *   Returns    : (1,1,1,1) tensor; data[0] == 0 (NO_FEAR) or 1 (FEAR).
 *
 * Architecture summary (both models):
 *   Input: (1, 57, 1, 10)
 *
 *   Block 1: DWConv(57->57, k=5, pad=1, groups=57) -> BN(57) -> ReLU
 *            PWConv(57->32, k=1)                   -> BN(32) -> ReLU -> MaxPool(2)
 *            Output: (1, 32, 1, 4)
 *
 *   [SE only - run_mobilecnn_se_1d]:
 *            SE: GlobalAvgPool -> Dense(32->8) -> ReLU
 *                              -> Dense(8->32)  -> HardSigmoid_Q7 [0,128]
 *                -> channel-wise multiply onto Block 1 output
 *
 *   Block 2: DWConv(32->32, k=5, pad=1, groups=32) -> BN(32) -> ReLU
 *            PWConv(32->64, k=1)                   -> BN(64) -> ReLU -> MaxPool(2)
 *            Output: (1, 64, 1, 1)
 *
 *   Head: Flatten -> Dense(64->1) -> Threshold(0)
 *
 * Parameter counts (conv/fc weights only, int32):
 *   MobileCNN-1D:    ~4.9K words (vs ~19.5K for CNN_1D_v2 baseline -- 4x fewer)
 *   MobileCNN-SE-1D: ~5.5K words (+ 552 for SE Dense layers)
 *
 * Activation arena peak:
 *   MobileCNN-1D:    1731 words (< ACT_ARENA_WORDS = 2048)
 *   MobileCNN-SE-1D: 1803 words (< ACT_ARENA_WORDS = 2048)
 *
 * Build:
 *   Compile with -DDEEPBINDI_MODEL=1 (MobileCNN-1D)
 *                or -DDEEPBINDI_MODEL=2 (MobileCNN-SE-1D)
 *   Optionally add -DDEEPBINDI_REAL_WEIGHTS to use trained weight headers:
 *     weights_mobile1d.h   (generated by export_mobile_weights.py --model mobile1d)
 *     weights_mobile_se.h  (generated by export_mobile_weights.py --model mobile_se)
 */

#ifndef MOBILE_MODELS_C_H
#define MOBILE_MODELS_C_H

#include <stdint.h>
#include "nn_runtime.h"

/**
 * run_mobilecnn_1d  --  MobileCNN-1D forward pass (Option A).
 * DWConv + PWConv blocks, no SE attention.
 */
Tensor *run_mobilecnn_1d(const int32_t *input_data);

/**
 * run_mobilecnn_se_1d  --  MobileCNN-SE-1D forward pass (Option B).
 * Same as run_mobilecnn_1d but with SE channel attention after Block 1.
 */
Tensor *run_mobilecnn_se_1d(const int32_t *input_data);

#endif /* MOBILE_MODELS_C_H */
